version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      docker: 18
  build:
    commands:
      - docker version
      - make build-docker
      - go test -v --tags="bdd" authority_test.go
